### ISSUE TITLE
KOPIS 데이터 스키마 조사

### ISSUE THREAD

**Issue by seokhyun-oh** [ladybugproject/documents#2]
### 개요
* [KOPIS OPEN API](http://www.kopis.or.kr/por/cs/openapi/openApiList.do?menuId=MNU_00074#n)에서 데이터 스키마 분석

![image](https://user-images.githubusercontent.com/13724074/61989493-2cbbb880-b06b-11e9-9e51-972098b475e4.png)

### 작업현황
- [x] 공연목록 API 스키마 분석
- [x] 공연상세 API 스키마 분석
- [x] 공연시설목록 API 스키마 분석
- [x] 공연시설상세 API 스키마 분석

**Comment by momentum1993** [comment]
KOPIS 오픈 API 조사 및 데이터베이스 스키마 구조

[DB_info.xlsx](https://github.com/ladybugproject/documents/files/3460049/DB_info.xlsx)

**Comment by seokhyun-oh** [comment]
@momentum1993 @SungBeom @eminem54 
<img width="1050" alt="스크린샷 2019-08-10 오후 12 44 16" src="https://user-images.githubusercontent.com/13724074/62817141-a3c57680-bb6c-11e9-8c00-1d8ea0bc6842.png">
